function params = generate_params(img_foler_path,rect_position_vis)
%%
%参数详情请调用 params.help 查看
%%
params = [];
params.img_folder_path = img_foler_path;
params.rect_position_vis = rect_position_vis;
params.rect_line_width = 4;
params.down_margin = 2;
params.right_margin = 2
params.margin = 2;
if length(rect_position_vis) == 1
    params.rect_line_color = {[1 0 0]};
else
    %color = ['r','g','b','c','m','y','k','w'];
    color = [{[1 0 0]},{[0 1 0]},{[0 0 1]},{[1 1 0]},{[1 0 1]},{[1 0 0]},{[0 1 1]},{[1 1 1]}];
    params.rect_line_color = {[1 0 0]};
    for i = 2:length(rect_position_vis)
        params.rect_line_color = [params.rect_line_color;color(i)];
    end
end
params.output_folder = './result';
params.save_each_crop_image = 1;
params.scale = ones(length(rect_position_vis)) * 1.0 / length(rect_position_vis);
params.mode = 0;

img_dir = [dir([params.img_folder_path,'/*.jpg']);...
    dir([params.img_folder_path,'/*.png']);...
    dir([params.img_folder_path,'/*.bmp']);...
    dir([params.img_folder_path,'/*.tif'])];
params.pics_each_row = length(img_dir);

params.side = 0;
params.radius = 0.618;

params.help = ['img_folder_path  放图片的文件夹位置，例如，"./Images"' 10 ...
    'rect_position_vis  待标注的矩形框的位置，矩形框形式[{x1,y1,w1,h1};{x2,y2,w2,h2}]' 10 ...
    '                   可以有多个矩形框，也可以只有单个矩形框，矩形框不要超过8个' 10 ...
    '                   注意传进来的格式是 N x 1 cell的数组，每个cell为[1 x 4]' 10 ...
    10 '剩余部分参数在返回的结构体params中，需要修改的话自行修改' 10 ...
    'rect_line_width  线框粗细  默认为3像素' 10 ...
    'rect_line_color  线框颜色  默认单框为红色' 10 ...
    '                          默认多框按照 红、绿、蓝、黄、品红、青蓝、白 的顺序给与目标框' 10 ...
    'show_name_on_each_figure  在图片中是否加上图片名字，默认为 否（0）' 10 ...
    'figure_name_pos  图片名字位置，默认为  [10 10]' 10 ...
    'text_color  所加文字颜色，默认为 [1 1 1]' 10 ...
    'font_size  所加文字大小，默认为 16' 10 ...
    'output_folder   结果输出文件夹  默认为 "./result"' 10 ...
    'save_each_crop_image  线框内图片剪切保存  默认为 是（1）' 10 ...
    'mode  输出图片模式 默认为0' 10 ...
    '      参数说明：0  右侧框' 10 ...
    '               1  下侧框' 10 ...
    '               2  只画框' 10 ...
    '               3  框在图里面' 10 ...
    '' 10 ...
    'scale  每个框之间的大小比例' 10 ...
    'pics_each_row  每行最多图片数，默认为  img_folder_path下的图片数目' 10 ...
    'down_margin  上下图片距离，默认为  0.01' 10 ...
    'right_margin  上下图片距离，默认为  0.01' 10 ...
    'margin  分块取得框和原图像的间距' 10 ...
    'side 如果mode为3，则决定框的位置，可取参数分别为 0,1,2,3 leftdown rightdown leftup rightup，0' 10 ...
    'radius 如果mode为3，则决定框的大小站比，默认为0.618' 10 ...
    ];
